import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PlausibleProvider from "next-plausible";
import { env } from "@/env";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PlausibleProvider
        domain={env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN}
        customDomain={env.NEXT_PUBLIC_PLAUSIBLE_API_HOST}
        taggedEvents
        enabled={
          !!env.NEXT_PUBLIC_PLAUSIBLE_DOMAIN &&
          !!env.NEXT_PUBLIC_PLAUSIBLE_API_HOST
        }
      >
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </PlausibleProvider>
    </html>
  );
}
